// Generates the icon data the client uses:
//   src/generated/tabler.json  every Tabler icon (outline + filled) for the picker, lazy-loaded
//   src/generated/emoji.json   every emoji with its name and keywords, lazy-loaded
//   src/generated/ui-icons.ts  the handful of icons the interface itself draws, bundled
// Run automatically by `npm run build` and `npm run dev`.
import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const out = join(root, 'src', 'generated');
mkdirSync(out, { recursive: true });

const read = (p) => JSON.parse(readFileSync(join(root, 'node_modules', p), 'utf8'));
const meta = read('@tabler/icons/icons.json');
const outline = read('@tabler/icons/tabler-nodes-outline.json');
const filled = read('@tabler/icons/tabler-nodes-filled.json');

const esc = (v) => String(v).replace(/&/g, '&amp;').replace(/"/g, '&quot;').replace(/</g, '&lt;');
const toSvg = (nodes) =>
  nodes
    .map(([tag, attrs]) => {
      const a = Object.entries(attrs)
        .filter(([k]) => k !== 'key')
        .map(([k, v]) => `${k}="${esc(v)}"`)
        .join(' ');
      return `<${tag} ${a}/>`;
    })
    .join('');

// ---- Tabler: [name, categoryIndex, keywords, svgBody, filled?]
const categories = [...new Set(Object.values(meta).map((m) => m.category || 'Other'))].sort();
const catIndex = new Map(categories.map((c, i) => [c, i]));
const icons = [];
for (const [name, nodes] of Object.entries(outline)) {
  const m = meta[name] ?? {};
  const keywords = (m.tags ?? []).map(String).filter((t) => !name.includes(t)).join(' ');
  icons.push([name, catIndex.get(m.category || 'Other') ?? 0, keywords, toSvg(nodes)]);
}
for (const [name, nodes] of Object.entries(filled)) {
  const m = meta[name] ?? {};
  const keywords = (m.tags ?? []).map(String).filter((t) => !name.includes(t)).join(' ');
  icons.push([name, catIndex.get(m.category || 'Other') ?? 0, keywords, toSvg(nodes), 1]);
}
writeFileSync(join(out, 'tabler.json'), JSON.stringify({ categories, icons }));

// ---- Emoji: [char, label, keywords, groupIndex]
const emoji = read('emojibase-data/en/compact.json');
const groupsMeta = read('emojibase-data/en/messages.json').groups;
const groups = groupsMeta.filter((g) => g.key !== 'component');
const groupIndex = new Map(groups.map((g, i) => [g.order, i]));
const emojiList = emoji
  .filter((e) => e.group !== undefined && groupIndex.has(e.group) && !/^regional indicator/.test(e.label))
  .sort((a, b) => (a.order ?? 0) - (b.order ?? 0))
  .map((e) => [e.unicode, e.label, (e.tags ?? []).join(' '), groupIndex.get(e.group)]);
writeFileSync(
  join(out, 'emoji.json'),
  JSON.stringify({ groups: groups.map((g) => g.message), emoji: emojiList }),
);

// ---- Interface icons, bundled with the app
const ui = [
  'adjustments-horizontal', 'alert-triangle', 'archive', 'archive-off', 'arrow-back-up', 'arrow-down',
  'arrow-forward-up', 'arrow-left', 'arrow-up', 'arrows-sort', 'at', 'ban', 'brush', 'check', 'checks',
  'chevron-down', 'chevron-left', 'chevron-right', 'circle', 'circle-check', 'circle-dashed', 'circle-dot',
  'cloud', 'cloud-check', 'cloud-off', 'cloud-up', 'code', 'color-swatch', 'command', 'copy', 'corner-down-right',
  'database', 'device-floppy', 'dots', 'download', 'eye', 'eye-off', 'file-text', 'filter', 'filter-off',
  'focus-2', 'folder-symlink', 'grip-vertical', 'hash', 'help', 'home', 'icons', 'indent-decrease',
  'indent-increase', 'info-circle', 'keyboard', 'layout-sidebar-left-collapse', 'layout-sidebar-left-expand',
  'list-tree', 'loader-2', 'lock', 'menu-2', 'minus', 'moon', 'mood-smile', 'note', 'notes', 'palette',
  'pencil', 'plus', 'refresh', 'search', 'select-all', 'selector', 'settings', 'sparkles', 'square',
  'square-check', 'square-minus', 'sun', 'sun-moon', 'tag', 'tags', 'trash', 'typography', 'upload', 'x',
  'zoom-in', 'zoom-out', 'layout-list', 'chevrons-down', 'chevrons-up', 'arrow-bar-to-down', 'bolt',
  'bookmark', 'bookmark-plus', 'template', 'star', 'flag', 'target', 'briefcase', 'calendar', 'rocket', 'bug',
  'inbox', 'users', 'variable',
];
// Default statuses and tags (seeded on first run) need their artwork too.
const seedIcons = ['circle', 'progress', 'hand-stop', 'circle-check', 'bulb', 'flame', 'hourglass', 'heart'];
const uiMap = {};
for (const name of [...new Set([...ui, ...seedIcons])]) {
  if (!outline[name]) throw new Error(`Unknown Tabler icon: ${name}`);
  uiMap[name] = toSvg(outline[name]);
}
writeFileSync(
  join(out, 'ui-icons.ts'),
  `// Generated by scripts/build-icons.mjs — do not edit.\n` +
    `export const uiIcons: Record<string, string> = ${JSON.stringify(uiMap, null, 1)};\n`,
);

console.log(
  `icons: ${icons.length} tabler (${Object.keys(outline).length} outline, ${Object.keys(filled).length} filled), ` +
    `${emojiList.length} emoji, ${Object.keys(uiMap).length} interface`,
);
